import { useEffect, useRef, useState } from "react"
import { Bell, Check, ExternalLink, X } from "lucide-react"
import { useNavigate } from "react-router-dom"
import { apiJson } from "../api"
type Notification = { id:number; type:string; title:string; message:string; read:boolean; created_at:string; href:string|null }
export default function NotificationBell() {
 const [items,setItems]=useState<Notification[]>([]),[open,setOpen]=useState(false),[unread,setUnread]=useState(0),[busy,setBusy]=useState<number[]>([])
 const root=useRef<HTMLDivElement>(null),navigate=useNavigate()
 async function load(){try{const data=await apiJson<{notifications:Notification[];unread_count:number}>("/notifications?page=1&page_size=8");setItems(data.notifications);setUnread(data.unread_count)}catch{}}
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(id)},[])
 useEffect(()=>{if(!open)return;function outside(e:PointerEvent){if(root.current&&!root.current.contains(e.target as Node))setOpen(false)}function escape(e:KeyboardEvent){if(e.key==="Escape")setOpen(false)}document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape)}},[open])
 async function openNotification(item:Notification){if(busy.includes(item.id))return;setBusy(v=>[...v,item.id]);try{if(!item.read){await apiJson("/notifications/"+item.id+"/read",{method:"PATCH"});setItems(v=>v.map(n=>n.id===item.id?{...n,read:true}:n));setUnread(v=>Math.max(0,v-1))}}catch{}finally{setBusy(v=>v.filter(id=>id!==item.id))}setOpen(false);if(item.href&&item.href.startsWith("/")&&!item.href.startsWith("//"))navigate(item.href)}
 async function readAll(){try{await apiJson("/notifications/read-all",{method:"PATCH"});setItems(v=>v.map(n=>({...n,read:true})));setUnread(0)}catch{}}
 return <div className="relative" ref={root}>
  <button type="button" onClick={()=>setOpen(v=>!v)} className="lms-profile-trigger relative flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-white/5" aria-label="Notifications" aria-expanded={open} aria-controls="notification-panel"><Bell size={17}/>{unread>0&&<span className="absolute -right-0.5 -top-0.5 flex min-h-4 min-w-4 items-center justify-center rounded-full bg-violet-500 px-1 text-[9px] font-bold">{unread>9?"9+":unread}</span>}</button>
  {open&&<section id="notification-panel" aria-label="Notifications panel" className="absolute right-0 top-12 z-[70] flex max-h-[min(80vh,520px)] w-[min(92vw,380px)] flex-col rounded-2xl border border-white/10 bg-[#0b101a] p-3 shadow-2xl">
   <header className="flex shrink-0 items-center justify-between gap-3 px-2 py-1"><p className="text-sm font-semibold">Notifications</p><div className="flex items-center gap-3">{unread>0&&<button type="button" onClick={readAll} className="text-xs text-violet-300 hover:text-white">Mark all read</button>}<button type="button" onClick={()=>setOpen(false)} className="flex h-8 w-8 items-center justify-center rounded-lg text-white/60 hover:bg-white/10 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400" aria-label="Close notifications"><X size={16}/></button></div></header>
   <div className="mt-2 min-h-0 flex-1 space-y-1 overflow-y-auto overscroll-contain" role="list">{items.length===0&&<p className="p-4 text-center text-xs text-white/35">You're all caught up.</p>}{items.map(item=><button type="button" role="listitem" key={item.id} disabled={busy.includes(item.id)} onClick={()=>void openNotification(item)} className={"flex w-full items-start gap-3 rounded-xl p-3 text-left hover:bg-white/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-violet-400 disabled:opacity-60 "+(item.read?"opacity-55":"bg-violet-400/[.06]")}><span className={"mt-1 h-2 w-2 shrink-0 rounded-full "+(item.read?"bg-white/15":"bg-violet-400")}/><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{item.title}</span><span className="mt-1 block text-xs leading-5 text-white/45">{item.message}</span><span className="mt-1 block text-[10px] text-white/25">{new Date(item.created_at).toLocaleString()}</span></span>{item.href?<ExternalLink size={13} className="mt-1 shrink-0 text-white/25"/>:item.read?<Check size={13} className="mt-1 shrink-0 text-emerald-300"/>:null}</button>)}</div>
  </section>}
 </div>
}
