KNOWLEDGE = [
    {"topic":"Primary Key","aliases":["primary key","primarykey"],"answer":"A primary key is a column, or combination of columns, that uniquely identifies each row in a relational table. It must be unique and cannot be NULL.","bullets":["Uniquely identifies each record","Cannot contain NULL values","A table has one primary-key constraint, which may contain multiple columns"],"terms":["uniqueness","NULL","relational table"],"tip":"For exams, remember: primary key = unique identity of a row."},
    {"topic":"Foreign Key","aliases":["foreign key","foreignkey"],"answer":"A foreign key is a column or set of columns that references a key in another table. It is used to connect related records and enforce referential integrity.","bullets":["References a key in another table","Creates relationships between tables","Helps enforce referential integrity"],"terms":["relationship","referential integrity","referenced table"],"tip":"Think: primary key identifies; foreign key connects."},
    {"topic":"Normalization","aliases":["normalization","database normalization"],"answer":"Normalization is the process of organizing relational data to reduce unnecessary redundancy and prevent update, insertion, and deletion anomalies.","bullets":["Reduces data redundancy","Improves data consistency","Uses normal forms such as 1NF, 2NF and 3NF"],"terms":["redundancy","normal forms","anomalies"],"tip":"A common exam question is why normalization is used: reduce redundancy and anomalies."},
    {"topic":"ACID Properties","aliases":["acid","acid properties","transaction properties"],"answer":"ACID describes four properties of reliable database transactions: Atomicity, Consistency, Isolation, and Durability.","bullets":["Atomicity: a transaction is all-or-nothing","Consistency: valid rules remain satisfied","Isolation: concurrent transactions are separated","Durability: committed changes persist"],"terms":["transactions","atomicity","isolation","durability"],"tip":"Memorize ACID in order: Atomicity, Consistency, Isolation, Durability."},
    {"topic":"Database Index","aliases":["indexing","database index","index"],"answer":"A database index is an auxiliary data structure that helps the database locate rows faster for suitable queries, at the cost of extra storage and write overhead.","bullets":["Can speed up lookups","Uses additional storage","Indexes also add work to inserts, updates and deletes"],"terms":["lookup","query performance","storage"],"tip":"Indexes improve read performance but are not free."},
    {"topic":"SQL JOIN","aliases":["join","sql join","joins"],"answer":"A SQL JOIN combines rows from two or more tables using a related column or condition.","bullets":["Combines related data from multiple tables","Common types include INNER, LEFT, RIGHT and FULL JOIN","The join condition determines which rows match"],"terms":["INNER JOIN","LEFT JOIN","join condition"],"tip":"Always identify which table contributes rows and what condition connects the tables."},
    {"topic":"MongoDB","aliases":["mongodb","mongo db"],"answer":"MongoDB is a document-oriented NoSQL database that stores records as BSON documents inside collections rather than rows inside relational tables.","bullets":["Uses collections and documents","Stores BSON-style document data","Supports flexible document structures"],"terms":["document","collection","NoSQL"],"tip":"Relational DB: tables and rows. MongoDB: collections and documents."},
    {"topic":"Supervised Learning","aliases":["supervised learning","supervised"],"answer":"Supervised learning trains a model using labeled examples where the desired target is known.","bullets":["Training data includes labels","Used for tasks such as classification and regression","The model learns a mapping from inputs to targets"],"terms":["labels","classification","regression"],"tip":"If the training examples have known target values, think supervised learning."},
    {"topic":"Overfitting","aliases":["overfitting","over fit"],"answer":"Overfitting occurs when a model learns the training data too closely and performs poorly on unseen data.","bullets":["Training performance can be very high","Generalization to unseen data is poor","Regularization, more data and simpler models can help"],"terms":["generalization","training data","regularization"],"tip":"High training performance does not guarantee good generalization."},
    {"topic":"Precision and Recall","aliases":["precision","recall","precision recall"],"answer":"Precision measures how many predicted positives are actually positive, while recall measures how many actual positives the model successfully finds.","bullets":["Precision focuses on correctness among predicted positives","Recall focuses on coverage of actual positives","Both are useful when accuracy alone is insufficient"],"terms":["true positive","false positive","false negative"],"tip":"Precision asks 'of what I predicted positive, how many were right?'; recall asks 'of all real positives, how many did I find?'."},
    {"topic":"Process","aliases":["process","operating system process"],"answer":"A process is a program in execution together with its current execution state and resources managed by the operating system.","bullets":["Has its own execution state","Uses operating-system-managed resources","A process can contain one or more threads"],"terms":["program","execution state","resources"],"tip":"Program is passive code; process is that program while it is executing."},
    {"topic":"Deadlock","aliases":["deadlock","dead lock"],"answer":"A deadlock is a state in which processes are permanently waiting for resources or events that cannot be obtained because of the circular dependency among them.","bullets":["Processes remain blocked","A circular wait can be involved","Operating systems use prevention, avoidance or detection strategies"],"terms":["circular wait","resource","blocked"],"tip":"Deadlock is about processes waiting indefinitely for each other or for unavailable resources."},
    {"topic":"TCP","aliases":["tcp","transmission control protocol"],"answer":"TCP is a connection-oriented transport-layer protocol that provides reliable, ordered delivery of a byte stream.","bullets":["Connection-oriented","Reliable and ordered delivery","Uses acknowledgements and retransmission mechanisms"],"terms":["transport layer","reliable delivery","connection-oriented"],"tip":"TCP emphasizes reliable ordered delivery; UDP emphasizes a simpler connectionless service."},
    {"topic":"UDP","aliases":["udp","user datagram protocol"],"answer":"UDP is a connectionless transport-layer protocol that sends datagrams without TCP-style guarantees of reliable ordered delivery.","bullets":["Connectionless","Low protocol overhead","Does not provide TCP-style reliable ordered delivery"],"terms":["datagram","transport layer","connectionless"],"tip":"Use the TCP-versus-UDP distinction to remember reliability versus lower overhead."},
    {"topic":"Embeddings","aliases":["embedding","embeddings","vector embedding"],"answer":"An embedding is a numerical vector representation of data such as text, designed so that useful semantic relationships can be compared mathematically.","bullets":["Represents content as numbers","Can capture semantic similarity","Often used for semantic search and retrieval"],"terms":["vector","semantic similarity","retrieval"],"tip":"In semantic search, text is converted into vectors and similar meanings can be compared."},
    {"topic":"Retrieval-Augmented Generation","aliases":["rag","retrieval augmented generation","retrieval-augmented generation"],"answer":"Retrieval-Augmented Generation combines retrieval of relevant external or stored information with a generation step so answers can use retrieved context.","bullets":["First retrieves relevant context","Uses that context to support the answer","Can reduce dependence on information stored only in model parameters"],"terms":["retrieval","context","generation"],"tip":"RAG = retrieve relevant knowledge, then use that knowledge to answer."}
]

def find_knowledge(text):
    q = (text or "").lower().strip()
    for item in KNOWLEDGE:
        if any(alias in q for alias in item["aliases"]):
            return item
    return None
