import { useEffect, useState } from "react"
import { BookOpen, LayoutDashboard, Users, Search, LogOut, User, ClipboardList, FileText } from "lucide-react"
import { useNavigate } from "react-router-dom"
import { API } from "../config"
type Overview={users:number;students:number;teachers:number;admins:number;courses:number;assignments:number;submissions:number}
type AdminUser={id:number;name:string;roll_no:string;role:string}
export default function Admin(){
 const navigate=useNavigate(),[overview,setOverview]=useState<Overview|null>(null),[users,setUsers]=useState<AdminUser[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("")
 const name=localStorage.getItem("name")||"Admin"
 useEffect(()=>{const token=localStorage.getItem("token");if(!token){navigate("/login");return}if(localStorage.getItem("role")!=="admin"){navigate("/dashboard");return}
 Promise.all([fetch(`${API}/admin/overview`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API}/admin/users`,{headers:{Authorization:`Bearer ${token}`}})]).then(async([a,b])=>{const ad=await a.json(),bd=await b.json();if(!a.ok)throw new Error(ad.detail||"Failed to load admin data");if(!b.ok)throw new Error(bd.detail||"Failed to load users");setOverview(ad);setUsers(bd)}).catch(e=>setError(e instanceof Error?e.message:"Failed to load admin data")).finally(()=>setLoading(false))},[navigate])
 function logout(){localStorage.clear();navigate("/login")}
 return <div className="min-h-screen bg-[#070b14] text-white"><aside className="fixed left-0 top-0 hidden h-screen w-64 border-r border-white/10 bg-[#0b101a] p-5 lg:block"><div className="flex items-center gap-3 px-3 py-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-black"><BookOpen size={21}/></div><div><h1 className="font-semibold">LMS</h1><p className="text-xs text-white/40">Admin Console</p></div></div><nav className="mt-8 space-y-2"><button className="flex w-full items-center gap-3 rounded-xl bg-white/10 px-4 py-3 text-sm"><LayoutDashboard size={18}/>Dashboard</button><button onClick={()=>navigate("/search")} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm text-white/50 hover:bg-white/5 hover:text-white"><Search size={18}/>AI Search</button></nav><button onClick={logout} className="absolute bottom-6 left-5 right-5 flex items-center gap-3 rounded-xl px-4 py-3 text-sm text-white/50 hover:bg-white/5 hover:text-white"><LogOut size={18}/>Logout</button></aside>
 <main className="lg:ml-64"><header className="flex items-center justify-between border-b border-white/10 px-6 py-5 lg:px-10"><div><p className="text-sm text-white/40">Admin Dashboard</p><h2 className="mt-1 text-2xl font-semibold">System Overview</h2></div><div className="flex items-center gap-3"><span className="hidden text-sm text-white/40 sm:block">{name}</span><button onClick={()=>navigate("/profile")} className="lms-profile-trigger flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-white/5" aria-label="Open profile"><User size={18}/></button></div></header>
 <section className="p-6 lg:p-10">{error&&<div className="mb-6 rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-300">{error}</div>}{loading?<div className="rounded-2xl border border-white/10 bg-white/[0.03] p-10 text-center text-white/40">Loading admin data...</div>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Users size={20}/>} title="Total Users" value={overview?.users||0}/><Stat icon={<BookOpen size={20}/>} title="Courses" value={overview?.courses||0}/><Stat icon={<ClipboardList size={20}/>} title="Assignments" value={overview?.assignments||0}/><Stat icon={<FileText size={20}/>} title="Submissions" value={overview?.submissions||0}/></div><div className="mt-8 rounded-2xl border border-white/10 bg-white/[0.035] p-6"><h3 className="text-lg font-semibold">Users</h3><p className="mt-1 mb-5 text-sm text-white/40">Student, teacher, and admin accounts in the LMS.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-white/10 text-white/40"><tr><th className="px-3 py-3">Name</th><th className="px-3 py-3">Roll Number</th><th className="px-3 py-3">Role</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-white/5 last:border-0"><td className="px-3 py-4">{u.name}</td><td className="px-3 py-4 text-white/50">{u.roll_no}</td><td className="px-3 py-4 capitalize text-white/60">{u.role}</td></tr>)}</tbody></table></div></div></>}</section></main></div>
}
function Stat({icon,title,value}:{icon:React.ReactNode;title:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-xl bg-white/10">{icon}</div><p className="text-sm text-white/40">{title}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
