import { useEffect, useMemo, useState } from "react"
import { BookOpen, LayoutDashboard, Users, Search, LogOut, User, ClipboardList, FileText, GraduationCap, ShieldCheck, Check } from "lucide-react"
import { useNavigate } from "react-router-dom"
import { API } from "../config"
type Overview={users:number;students:number;teachers:number;admins:number;courses:number;assignments:number;submissions:number}
type AdminUser={id:number;name:string;roll_no:string;role:string;section:string}
export default function Admin(){
 const navigate=useNavigate(),[overview,setOverview]=useState<Overview|null>(null),[users,setUsers]=useState<AdminUser[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("")
 const name=localStorage.getItem("name")||"Admin"
 const teachers=useMemo(()=>users.filter(u=>u.role==="teacher"),[users])
 const students=useMemo(()=>users.filter(u=>u.role==="student"),[users])
 const [saving,setSaving]=useState<number|null>(null)
 async function assignSection(id:number,section:string){
  const token=localStorage.getItem("token");if(!token)return
  setSaving(id);setError("")
  try{
   const r=await fetch(`${API}/admin/teachers/${id}/section?section=${encodeURIComponent(section)}`,{method:"PUT",headers:{Authorization:`Bearer ${token}`}})
   const d=await r.json();if(!r.ok)throw new Error(d.detail||"Unable to assign section")
   setUsers(list=>list.map(u=>u.id===id?{...u,section:d.section}:u))
  }catch(e){setError(e instanceof Error?e.message:"Unable to assign section")}
  finally{setSaving(null)}
 }
 useEffect(()=>{const token=localStorage.getItem("token");if(!token){navigate("/login");return}if(localStorage.getItem("role")!=="admin"){navigate("/dashboard");return}
 Promise.all([fetch(`${API}/admin/overview`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API}/admin/users`,{headers:{Authorization:`Bearer ${token}`}})]).then(async([a,b])=>{const ad=await a.json(),bd=await b.json();if(!a.ok)throw new Error(ad.detail||"Failed to load admin data");if(!b.ok)throw new Error(bd.detail||"Failed to load users");setOverview(ad);setUsers(bd)}).catch(e=>setError(e instanceof Error?e.message:"Failed to load admin data")).finally(()=>setLoading(false))},[navigate])
 function logout(){localStorage.clear();navigate("/login")}
 return <div className="min-h-screen bg-[#070b14] text-white"><aside className="fixed left-0 top-0 hidden h-screen w-64 border-r border-white/10 bg-[#0b101a] p-5 lg:block"><div className="flex items-center gap-3 px-3 py-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-black"><BookOpen size={21}/></div><div><h1 className="font-semibold">LMS</h1><p className="text-xs text-white/40">Admin Console</p></div></div><nav className="mt-8 space-y-2"><button className="flex w-full items-center gap-3 rounded-xl bg-white/10 px-4 py-3 text-sm"><LayoutDashboard size={18}/>Dashboard</button><button onClick={()=>navigate("/search")} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm text-white/50 hover:bg-white/5 hover:text-white"><Search size={18}/>AI Search</button></nav><button onClick={logout} className="absolute bottom-6 left-5 right-5 flex items-center gap-3 rounded-xl px-4 py-3 text-sm text-white/50 hover:bg-white/5 hover:text-white"><LogOut size={18}/>Logout</button></aside>
 <main className="lg:ml-64"><header className="flex items-center justify-between border-b border-white/10 px-6 py-5 lg:px-10"><div><p className="text-sm text-white/40">Admin Dashboard</p><h2 className="mt-1 text-2xl font-semibold">System Overview</h2></div><div className="flex items-center gap-3"><span className="hidden text-sm text-white/40 sm:block">{name}</span><button onClick={()=>navigate("/profile")} className="lms-profile-trigger flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-white/5" aria-label="Open profile"><User size={18}/></button></div></header>
 <section className="p-6 lg:p-10">{error&&<div className="mb-6 rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-300">{error}</div>}{loading?<div className="rounded-2xl border border-white/10 bg-white/[0.03] p-10 text-center text-white/40">Loading admin data...</div>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Users size={20}/>} title="Total Users" value={overview?.users||0}/><Stat icon={<BookOpen size={20}/>} title="Courses" value={overview?.courses||0}/><Stat icon={<ClipboardList size={20}/>} title="Assignments" value={overview?.assignments||0}/><Stat icon={<FileText size={20}/>} title="Submissions" value={overview?.submissions||0}/></div><div className="mt-8 grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
  <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-6">
   <div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] text-violet-300/70">Faculty management</p><h3 className="mt-2 text-xl font-semibold">Assign faculty sections</h3><p className="mt-1 text-sm text-white/40">Only Admin can decide which section each faculty member handles.</p></div><div className="lms-icon flex h-11 w-11 items-center justify-center rounded-xl"><Users size={19}/></div></div>
   <div className="mt-6 space-y-3">{teachers.length?teachers.map(u=><div key={u.id} className="rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><GraduationCap size={16} className="text-violet-300"/><p className="font-medium">{u.name}</p></div><p className="mt-1 text-xs text-white/35">{u.roll_no} · Current: {u.section}</p></div><div className="flex items-center gap-2"><select value={u.section==="Unassigned"?"":u.section} onChange={e=>assignSection(u.id,e.target.value)} disabled={saving===u.id} className="lms-input min-w-28 py-2 text-sm"><option value="" disabled>{saving===u.id?"Saving...":"Assign section"}</option>{["A1","A2","A3","A4","A5","A6","A7"].map(s=><option key={s} value={s}>{s}</option>)}</select>{u.section!=="Unassigned"&&saving!==u.id&&<Check size={17} className="text-emerald-300"/>}</div></div></div>):<div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-white/30">No faculty registered yet.</div>}</div>
  </div>
  <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-6">
   <div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-cyan-300/70">Registered learners</p><h3 className="mt-2 text-xl font-semibold">Students</h3><p className="mt-1 text-sm text-white/40">All student accounts registered in the LMS.</p></div><div className="lms-icon flex h-11 w-11 items-center justify-center rounded-xl"><GraduationCap size={19}/></div></div>
   <div className="mt-5 space-y-2">{students.length?students.map(u=><div key={u.id} className="flex items-center justify-between rounded-xl border border-white/8 bg-white/[.02] px-4 py-3"><div><p className="text-sm font-medium">{u.name}</p><p className="mt-1 text-xs text-white/35">{u.roll_no}</p></div><span className="rounded-full border border-cyan-400/15 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-200">{u.section === "Unassigned" ? "Awaiting allocation" : u.section}</span></div>):<div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-white/30">No students registered yet.</div>}</div>
  </div>
 </div>
 <div className="mt-5 rounded-2xl border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center gap-2 text-white/70"><ShieldCheck size={17}/><p className="text-sm font-medium">Registered admins</p></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{users.filter(u=>u.role==="admin").map(u=><div key={u.id} className="rounded-xl border border-white/8 p-3 text-sm"><p>{u.name}</p><p className="mt-1 text-xs text-white/30">{u.roll_no}</p></div>)}</div></div></>}</section></main></div>
}
function Stat({icon,title,value}:{icon:React.ReactNode;title:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="mb-5 flex h-10 w-10 items-center justify-center rounded-xl bg-white/10">{icon}</div><p className="text-sm text-white/40">{title}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
