import {useEffect,useState} from "react"
import {Users,BookOpen,ClipboardList,ShieldCheck} from "lucide-react"
import {useNavigate} from "react-router-dom"
import AppLayout from "../components/AppLayout"
import {apiJson} from "../api"
type Overview={users:number;students:number;teachers:number;admins:number;courses:number;assignments:number;submissions:number}
type User={id:number;name:string;email:string;role:string;section:string}
export default function Admin(){const navigate=useNavigate();const [overview,setOverview]=useState<Overview|null>(null);const [users,setUsers]=useState<User[]>([]);const [error,setError]=useState("");useEffect(()=>{if(!localStorage.getItem("token")){navigate("/login");return}if(localStorage.getItem("role")!=="admin"){navigate("/dashboard");return}Promise.all([apiJson<Overview>("/admin/overview"),apiJson<User[]>("/admin/users")]).then(([o,u])=>{setOverview(o);setUsers(u)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load admin console"))},[navigate]);return <AppLayout title="System Overview" subtitle="Admin Console"><section className="lms-grid min-h-[calc(100vh-76px)] p-4 sm:p-6 lg:p-10"><div className="mx-auto max-w-7xl">{error&&<div role="alert" className="rounded-2xl border border-red-400/20 bg-red-400/10 p-5 text-sm text-red-300">{error}</div>}{overview&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users size={18}/>} label="Users" value={overview.users}/><Metric icon={<BookOpen size={18}/>} label="Courses" value={overview.courses}/><Metric icon={<ClipboardList size={18}/>} label="Assignments" value={overview.assignments}/><Metric icon={<ShieldCheck size={18}/>} label="Admins" value={overview.admins}/></div>}<div className="mt-6 lms-card rounded-3xl p-6"><h2 className="text-xl font-semibold">Users</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="text-xs text-white/30"><tr><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Role</th><th className="p-3">Section</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-white/5"><td className="p-3">{u.name}</td><td className="p-3 text-white/50">{u.email}</td><td className="p-3">{u.role}</td><td className="p-3 text-white/50">{u.section}</td></tr>)}</tbody></table></div></div></div></section></AppLayout>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="lms-stat rounded-2xl p-5"><div className="lms-icon mb-4 flex h-10 w-10 items-center justify-center rounded-xl">{icon}</div><p className="text-sm text-white/40">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
