import {useEffect,useState} from "react"
import {ClipboardList,Plus,X,Clock,CheckCircle2,Send} from "lucide-react"
import {useNavigate} from "react-router-dom"
import AppLayout from "../components/AppLayout"
import {apiJson} from "../api"
type Course={id:number;title:string;description:string;teacher_id:number}
type Assignment={id:number;title:string;description:string;course_id:number;teacher_id:number;type:string;start_time:string|null;end_time:string|null;duration_minutes:number|null;deadline:string|null;status:"upcoming"|"open"|"closed";submitted:boolean;handout?:{id:string;title:string;filename:string}|null}
type Question={id:number;question_text:string;question_type:"mcq"|"descriptive";max_marks:number;options?:{id:number;option_text:string}[]}
export default function Assignments(){
 const navigate=useNavigate();const role=localStorage.getItem("role")||"student";const [courses,setCourses]=useState<Course[]>([]);const [items,setItems]=useState<Assignment[]>([]);const [selected,setSelected]=useState<Assignment|null>(null);const [questions,setQuestions]=useState<Question[]>([]);const [answers,setAnswers]=useState<Record<number,{selected_option_id?:number;student_answer?:string}>>({});const [error,setError]=useState("");const [message,setMessage]=useState("");const [showCreate,setShowCreate]=useState(false);const [loading,setLoading]=useState(true);const [creating,setCreating]=useState(false);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [courseId,setCourseId]=useState("");const [type,setType]=useState("assignment");const [start,setStart]=useState("");const [end,setEnd]=useState("");const [duration,setDuration]=useState("")
 async function load(){try{const [cs,as]=await Promise.all([apiJson<Course[]>("/my-courses"),apiJson<Assignment[]>("/my-assignments")]);setCourses(cs);setItems(as);if(cs[0])setCourseId(String(cs[0].id))}catch(e){setError(e instanceof Error?e.message:"Failed to load assessments")}finally{setLoading(false)}}
 useEffect(()=>{if(!localStorage.getItem("token")){navigate("/login");return}load()},[navigate])
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("assignment_id");if(id&&items.length){const a=items.find(x=>x.id===Number(id));if(a)open(a)}},[items])
 async function open(a:Assignment){setSelected(a);setError("");setMessage("");try{const q=await apiJson<Question[]>("/assignments/"+a.id+"/questions");setQuestions(q);setAnswers(Object.fromEntries(q.map(x=>[x.id,x.question_type==="mcq"?{}:{student_answer:""}])))}catch(e){setError(e instanceof Error?e.message:"Unable to load questions")}}
 async function create(e:React.FormEvent){e.preventDefault();setCreating(true);setError("");try{const form=new FormData();form.append("course_id",courseId);form.append("title",title);form.append("description",description);form.append("type",type);if(start)form.append("start_time",new Date(start).toISOString());if(end)form.append("end_time",new Date(end).toISOString());if(duration)form.append("duration_minutes",duration);await apiJson("/assignments",{method:"POST",body:form});setMessage("Assessment created and enrolled students notified.");setShowCreate(false);setTitle("");setDescription("");setStart("");setEnd("");setDuration("");await load()}catch(e){setError(e instanceof Error?e.message:"Creation failed")}finally{setCreating(false)}}
 async function submit(){if(!selected)return;try{await apiJson("/assignments/"+selected.id+"/submit-exam",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assignment_id:selected.id,answers:Object.entries(answers).map(([id,a])=>({question_id:Number(id),...a}))})});setMessage("Assessment submitted successfully.");await load();setSelected(null)}catch(e){setError(e instanceof Error?e.message:"Submission failed")}}
 return <AppLayout title="Assignments & Tests" subtitle="Assessment Workspace"><section className="lms-grid min-h-[calc(100vh-76px)] p-4 sm:p-6 lg:p-10"><div className="mx-auto max-w-6xl">
 {error&&<div role="alert" className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-300">{error}</div>}{message&&<div role="status" className="mb-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-300">{message}</div>}
 <div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">{role==="teacher"?"Assessment Workspace":"My Assessments"}</h2><p className="mt-1 text-sm text-white/40">{items.length} assessment{items.length===1?"":"s"}</p></div>{role==="teacher"&&<button onClick={()=>setShowCreate(true)} className="lms-btn-primary rounded-xl px-4 py-2.5 text-sm"><Plus size={16}/>Create assessment</button>}</div>
 {loading?<div className="mt-8 text-sm text-white/35">Loading assessments...</div>:<div className="mt-6 grid gap-4 md:grid-cols-2">{items.map(a=><button key={a.id} onClick={()=>open(a)} className="lms-card rounded-2xl p-5 text-left"><div className="flex items-start gap-3"><div className="lms-icon flex h-10 w-10 items-center justify-center rounded-xl"><ClipboardList size={18}/></div><div className="min-w-0 flex-1"><p className="font-medium">{a.title}</p><p className="mt-1 text-xs text-white/35">{a.type} · {a.status}</p><p className="mt-2 line-clamp-2 text-sm text-white/40">{a.description}</p></div></div>{a.deadline&&<p className="mt-4 flex items-center gap-2 text-xs text-white/30"><Clock size={13}/>Due {new Date(a.deadline).toLocaleString()}</p>}{a.submitted&&<p className="mt-3 flex items-center gap-2 text-xs text-emerald-300"><CheckCircle2 size={13}/>Submitted</p>}</button>)}</div>}
 {selected&&role==="student"&&<div className="lms-modal fixed inset-0 z-50 flex justify-center p-4" role="dialog" aria-modal="true"><div className="lms-modal-panel lms-card rounded-3xl p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs text-violet-300">{selected.type}</p><h3 className="mt-1 text-xl font-semibold">{selected.title}</h3></div><button onClick={()=>setSelected(null)} className="lms-btn-secondary h-9 w-9 rounded-lg" aria-label="Close assessment"><X size={17}/></button></div><div className="mt-6 space-y-5">{questions.map((q,i)=><div key={q.id} className="rounded-2xl border border-white/10 p-5"><p className="text-xs text-white/30">Question {i+1} · {q.max_marks} marks</p><p className="mt-2 font-medium">{q.question_text}</p>{q.question_type==="mcq"?<div className="mt-4 space-y-2">{q.options?.map(o=><label key={o.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 p-3 text-sm hover:bg-white/5"><input type="radio" name={"q"+q.id} checked={answers[q.id]?.selected_option_id===o.id} onChange={()=>setAnswers(a=>({...a,[q.id]:{selected_option_id:o.id}}))}/>{o.option_text}</label>)}</div>:<textarea value={answers[q.id]?.student_answer||""} onChange={e=>setAnswers(a=>({...a,[q.id]:{student_answer:e.target.value}}))} rows={5} className="lms-input mt-4 resize-y" placeholder="Write your answer"/>}</div>)}</div><button onClick={submit} className="lms-btn-primary mt-6 w-full rounded-xl py-3 text-sm"><Send size={16}/>Submit assessment</button></div></div>}
 {showCreate&&<div className="lms-modal fixed inset-0 z-50 flex justify-center p-4" role="dialog" aria-modal="true"><div className="lms-modal-panel lms-card rounded-3xl p-6 sm:p-8"><div className="flex items-center justify-between"><h3 className="font-semibold">Create assessment</h3><button onClick={()=>setShowCreate(false)} aria-label="Close dialog"><X size={17}/></button></div><form onSubmit={create} className="mt-6 space-y-4"><Field label="Course"><select value={courseId} onChange={e=>setCourseId(e.target.value)} className="lms-input">{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><Field label="Title"><input value={title} onChange={e=>setTitle(e.target.value)} required className="lms-input"/></Field><Field label="Description"><textarea value={description} onChange={e=>setDescription(e.target.value)} required rows={4} className="lms-input resize-y"/></Field><Field label="Type"><select value={type} onChange={e=>setType(e.target.value)} className="lms-input"><option value="assignment">Assignment</option><option value="test">Test</option><option value="exam">Exam</option></select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Start"><input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} className="lms-input"/></Field><Field label="Due"><input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className="lms-input"/></Field></div><Field label="Duration (minutes)"><input type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)} className="lms-input"/></Field><button disabled={creating} className="lms-btn-primary w-full rounded-xl py-3 text-sm disabled:opacity-40">{creating?"Creating...":"Create assessment"}</button></form></div></div>}
 </div></section></AppLayout>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm text-white/60">{label}</span>{children}</label>}
