import { useEffect,useState } from "react"
import { BookOpen,LayoutDashboard,ClipboardList,Award,Search,LogOut,User,Check,FileText,Download } from "lucide-react"
import { useNavigate } from "react-router-dom"
const API="http://127.0.0.1:8000"
type Course={id:number;title:string;description:string;teacher_id:number};type Resource={id:string;title:string;filename:string}
export default function Courses(){
 const navigate=useNavigate(),[courses,setCourses]=useState<Course[]>([]),[mine,setMine]=useState<Course[]>([]),[res,setRes]=useState<Record<number,Resource[]>>({}),[error,setError]=useState("")
 const role=localStorage.getItem("role")||"student",name=localStorage.getItem("name")||"User"
 useEffect(()=>{const t=localStorage.getItem("token");if(!t){navigate("/login");return}load(t)},[navigate])
 async function load(t:string){try{const all=await fetch(API+"/courses").then(r=>r.json());setCourses(all);const m=role==="student"?await fetch(API+"/my-courses",{headers:{Authorization:"Bearer "+t}}).then(r=>r.json()):all.filter((c:Course)=>c.teacher_id===Number(localStorage.getItem("userId")));setMine(m);const pairs=await Promise.all(m.map(async(c:Course)=>[c.id,await fetch(API+"/courses/"+c.id+"/resources",{headers:{Authorization:"Bearer "+t}}).then(r=>r.ok?r.json():[])] as const));setRes(Object.fromEntries(pairs))}catch{setError("Failed to load courses")}}
 async function enroll(id:number){const t=localStorage.getItem("token");if(!t)return;const r=await fetch(API+"/enroll",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+t},body:JSON.stringify({course_id:id})});if(r.ok)load(t)}
 function logout(){localStorage.clear();navigate("/login")}
 return <div className="min-h-screen bg-[#070b14] text-white"><aside className="fixed left-0 top-0 hidden h-screen w-64 border-r border-white/10 bg-[#0b101a] p-5 lg:block"><Brand/><nav className="mt-8 space-y-2"><Nav onClick={()=>navigate(role==="teacher"?"/teacher":"/dashboard")} icon={<LayoutDashboard size={18}/>} text="Dashboard"/><Nav active onClick={()=>{}} icon={<BookOpen size={18}/>} text="My Courses"/><Nav onClick={()=>navigate("/assignments")} icon={<ClipboardList size={18}/>} text="Assignments"/><Nav onClick={()=>navigate("/marks")} icon={<Award size={18}/>} text="Marks"/><Nav onClick={()=>navigate("/search")} icon={<Search size={18}/>} text="AI Search"/></nav><button onClick={logout} className="nav absolute bottom-6 left-5 right-5"><LogOut size={18}/>Logout</button></aside><main className="lg:ml-64"><header className="border-b border-white/10 px-6 py-5 lg:px-10"><p className="text-sm text-white/40">{role==="teacher"?"Teacher":"Student"}</p><h2 className="mt-1 text-2xl font-semibold">Course Library</h2></header><section className="p-6 lg:p-10">{error&&<div className="mb-6 text-sm text-red-300">{error}</div>}<h3 className="text-xl font-semibold">{role==="student"?"Available Courses":"My Courses"}</h3><p className="mt-1 text-sm text-white/40">Access course resources and teacher-uploaded PDFs.</p><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{courses.map(c=>{const enrolled=mine.some(x=>x.id===c.id);return <div key={c.id} className="rounded-2xl border border-white/10 bg-white/[0.035] p-6"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10"><BookOpen size={20}/></div>{role==="student"&&enrolled&&<span className="flex items-center gap-1 rounded-full bg-green-400/10 px-3 py-1 text-xs text-green-300"><Check size={13}/>Enrolled</span>}</div><h4 className="mt-6 text-lg font-medium">{c.title}</h4><p className="mt-2 text-sm text-white/40">{c.description}</p>{role==="student"&&!enrolled?<button onClick={()=>enroll(c.id)} className="mt-6 w-full rounded-xl bg-white py-3 text-sm font-medium text-black">Enroll Now</button>:enrolled&&<div className="mt-6 border-t border-white/10 pt-5"><p className="text-sm font-medium">Course Materials</p>{!res[c.id]?.length?<p className="mt-2 text-xs text-white/30">No PDFs uploaded yet.</p>:<div className="mt-3 space-y-2">{res[c.id].map(x=><a key={x.id} href={API+"/resources/"+x.id+"/download"} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-white/10 px-4 py-3 text-sm"><span className="flex min-w-0 items-center gap-2"><FileText size={16}/><span className="truncate">{x.title}</span></span><Download size={15}/></a>)}</div>}</div>}</div>})}</div></section></main></div>
}
function Brand(){return <div className="flex items-center gap-3 px-3 py-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-black"><BookOpen size={21}/></div><div><h1 className="font-semibold">LMS</h1><p className="text-xs text-white/40">Learning Platform</p></div></div>}
function Nav({onClick,active,icon,text}:{onClick:()=>void;active?:boolean;icon:React.ReactNode;text:string}){return <button onClick={onClick} className={"nav "+(active?"active":"")}>{icon}{text}</button>}
