import {useEffect,useState} from "react"
import {BookOpen,ClipboardList,Award,BrainCircuit,TrendingUp} from "lucide-react"
import {useNavigate} from "react-router-dom"
import AppLayout from "../components/AppLayout"
import {apiJson} from "../api"
type Course={id:number;title:string;description:string}
type Submission={id:number;assignment_id:number;marks:number|null}
type Insight={overall:{progress:number;average_marks:number|null;graded:number;submitted:number;total_assessments:number};next_actions:{title:string;detail:string;action:string}[]}
export default function Dashboard(){
 const navigate=useNavigate();const [courses,setCourses]=useState<Course[]>([]);const [subs,setSubs]=useState<Submission[]>([]);const [insight,setInsight]=useState<Insight|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("")
 useEffect(()=>{if(!localStorage.getItem("token")){navigate("/login");return}if(localStorage.getItem("role")!=="student"){navigate(localStorage.getItem("role")==="teacher"?"/teacher":"/admin");return};Promise.all([apiJson<Course[]>("/my-courses"),apiJson<Submission[]>("/my-submissions")]).then(([c,s])=>{setCourses(c);setSubs(s);apiJson<Insight>("/learning-insights").then(setInsight).catch(()=>{})}).catch(e=>setError(e instanceof Error?e.message:"Unable to load dashboard")).finally(()=>setLoading(false))},[navigate])
 return <AppLayout title="Dashboard" subtitle="Student Workspace"><section className="lms-grid min-h-[calc(100vh-76px)] p-4 sm:p-6 lg:p-10"><div className="mx-auto max-w-7xl">
 {error&&<div role="alert" className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-300">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<BookOpen size={19}/>} label="My Courses" value={courses.length}/><Stat icon={<ClipboardList size={19}/>} label="Submissions" value={subs.length}/><Stat icon={<Award size={19}/>} label="Graded" value={subs.filter(s=>s.marks!==null).length}/><Stat icon={<Award size={19}/>} label="Marks" value={subs.reduce((n,s)=>n+(s.marks||0),0)}/></div>
 <div className="mt-8 lms-hero rounded-3xl p-6 sm:p-8"><p className="text-sm text-violet-300">Personal learning space</p><h2 className="mt-2 text-2xl font-semibold">Keep your learning momentum.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/40">Courses, assessments, marks and authorized AI tools stay in one consistent workspace.</p><div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>navigate("/courses")} className="lms-btn-secondary rounded-xl px-4 py-2.5 text-sm">Browse courses</button><button onClick={()=>navigate("/copilot")} className="lms-btn-primary rounded-xl px-4 py-2.5 text-sm"><BrainCircuit size={16}/>Study Copilot</button></div></div>
 <div className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="lms-card rounded-3xl p-6"><div className="flex items-center gap-2"><BookOpen size={18} className="text-violet-300"/><h3 className="font-semibold">My Courses</h3></div>{loading?<p className="mt-6 text-sm text-white/35">Loading...</p>:courses.length?<div className="mt-5 grid gap-3 md:grid-cols-2">{courses.map(c=><div key={c.id} className="rounded-xl border border-white/10 bg-white/[.02] p-4"><p className="font-medium">{c.title}</p><p className="mt-1 text-xs leading-5 text-white/35">{c.description}</p></div>)}</div>:<p className="mt-5 text-sm text-white/35">No enrolled courses yet.</p>}</div><div className="lms-card rounded-3xl p-6"><div className="flex items-center gap-2"><TrendingUp size={18} className="text-cyan-300"/><h3 className="font-semibold">Learning progress</h3></div>{insight?<><p className="mt-5 text-3xl font-semibold">{insight.overall.progress}%</p><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width:insight.overall.progress+"%"}}/></div><div className="mt-5 space-y-2">{insight.next_actions.slice(0,3).map((a,i)=><button key={i} onClick={()=>navigate(a.action==="search"?"/search":a.action==="courses"?"/courses":"/assignments")} className="w-full rounded-xl border border-white/10 p-3 text-left hover:bg-white/5"><p className="text-sm font-medium">{a.title}</p><p className="mt-1 text-xs text-white/35">{a.detail}</p></button>)}</div></>:<p className="mt-5 text-sm text-white/35">Learning insights will appear here.</p>}</div></div>
 </div></section></AppLayout>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="lms-stat rounded-2xl p-5"><div className="lms-icon mb-4 flex h-10 w-10 items-center justify-center rounded-xl">{icon}</div><p className="text-sm text-white/40">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
