import {useEffect,useState} from "react"
import {Award,RefreshCw} from "lucide-react"
import {useNavigate} from "react-router-dom"
import AppLayout from "../components/AppLayout"
import {apiJson} from "../api"
type Submission={id:number;assignment_id:number;assignment_title?:string;student_id:number;student_name?:string;marks:number|null;max_marks?:number}
export default function Marks(){
 const navigate=useNavigate();const role=localStorage.getItem("role")||"student";const [items,setItems]=useState<Submission[]>([]);const [error,setError]=useState("");const [saving,setSaving]=useState<number|null>(null);const [values,setValues]=useState<Record<number,string>>({})
 async function load(){try{setItems(await apiJson<Submission[]>(role==="teacher"?"/teacher/submissions":"/my-marks"));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load marks")}}
 useEffect(()=>{if(!localStorage.getItem("token")){navigate("/login");return}if(role==="admin"){navigate("/admin");return}load()},[navigate,role])
 async function grade(id:number){const value=Number(values[id]);if(!Number.isInteger(value)||value<0||value>100){setError("Marks must be a whole number from 0 to 100");return}setSaving(id);try{await apiJson("/submissions/"+id+"/marks?marks="+value,{method:"PUT"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update marks")}finally{setSaving(null)}}
 return <AppLayout title={role==="teacher"?"Student Marks":"Marks"} subtitle="Academic Performance"><section className="lms-grid min-h-[calc(100vh-76px)] p-4 sm:p-6 lg:p-10"><div className="mx-auto max-w-6xl">{error&&<div role="alert" className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-300">{error}</div>}<div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">{role==="teacher"?"Submissions to grade":"My results"}</h2><p className="mt-1 text-sm text-white/40">{items.length} record{items.length===1?"":"s"}</p></div><button onClick={load} className="lms-btn-secondary rounded-xl px-3 py-2 text-sm"><RefreshCw size={15}/>Refresh</button></div><div className="mt-6 space-y-3">{items.map(item=><div key={item.id} className="lms-card rounded-2xl p-5"><div className="flex flex-wrap items-center gap-4"><div className="lms-icon flex h-10 w-10 items-center justify-center rounded-xl"><Award size={18}/></div><div className="min-w-0 flex-1"><p className="font-medium">{item.assignment_title||"Assessment #"+item.assignment_id}</p>{role==="teacher"&&<p className="mt-1 text-xs text-white/35">{item.student_name||"Student #"+item.student_id}</p>}</div>{item.marks!==null?<span className="text-lg font-semibold">{item.marks}{item.max_marks?"/"+item.max_marks:""}</span>:role==="teacher"?<div className="flex gap-2"><input value={values[item.id]||""} onChange={e=>setValues(v=>({...v,[item.id]:e.target.value}))} type="number" min="0" max="100" className="lms-input w-24"/><button onClick={()=>grade(item.id)} disabled={saving===item.id} className="lms-btn-primary rounded-xl px-4 py-2 text-sm">{saving===item.id?"Saving...":"Grade"}</button></div>:<span className="text-sm text-white/35">Pending grading</span>}</div></div>)}{!items.length&&<div className="lms-empty rounded-2xl p-10 text-center text-sm text-white/35">No marks or submissions yet.</div>}</div></div></section></AppLayout>
}
