import {useEffect,useState} from "react"
import {UserRound,GraduationCap,Users,ShieldCheck,CalendarDays} from "lucide-react"
import {useNavigate} from "react-router-dom"
import AppLayout from "../components/AppLayout"
import {apiJson} from "../api"
type Course={id:number;title:string;description:string}
type Upcoming={id:number;title:string;type:string;course:string;deadline:string}
type ProfileData={id:number;name:string;email:string;role:string;section:string;courses:Course[];upcoming:Upcoming[]}
export default function Profile(){
 const navigate=useNavigate();const [data,setData]=useState<ProfileData|null>(null);const [error,setError]=useState("")
 useEffect(()=>{if(!localStorage.getItem("token")){navigate("/login");return}apiJson<ProfileData>("/profile").then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load profile"))},[navigate])
 const icon=data?.role==="teacher"?<Users size={22}/>:data?.role==="admin"?<ShieldCheck size={22}/>:<GraduationCap size={22}/>
 return <AppLayout title="Profile" subtitle="Account"><section className="lms-grid min-h-[calc(100vh-76px)] p-4 sm:p-6 lg:p-10"><div className="mx-auto max-w-5xl">{error&&<div role="alert" className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-300">{error}</div>}{data&&<><div className="lms-hero rounded-3xl p-6 sm:p-8"><div className="flex items-center gap-4"><div className="profile-avatar flex h-16 w-16 items-center justify-center rounded-2xl">{icon}</div><div><h2 className="text-2xl font-semibold">{data.name}</h2><p className="mt-1 text-sm text-white/40">{data.email}</p><span className="profile-role mt-2 inline-block">{data.role}</span></div></div></div><div className="mt-6 grid gap-5 md:grid-cols-2"><div className="lms-card rounded-3xl p-6"><h3 className="font-semibold">Account details</h3><div className="mt-5 space-y-3"><Info label="Section" value={data.section}/><Info label="Role" value={data.role}/></div></div><div className="lms-card rounded-3xl p-6"><h3 className="font-semibold">Upcoming assessments</h3><div className="mt-5 space-y-2">{data.upcoming.slice(0,5).map(a=><button key={a.id} onClick={()=>navigate("/assignments?assignment_id="+a.id)} className="flex w-full items-center gap-3 rounded-xl border border-white/10 p-3 text-left hover:bg-white/5"><CalendarDays size={17} className="text-violet-300"/><span className="min-w-0 flex-1"><span className="block text-sm">{a.title}</span><span className="text-xs text-white/35">{a.course} · {new Date(a.deadline).toLocaleString()}</span></span></button>)}{!data.upcoming.length&&<p className="text-sm text-white/35">No upcoming assessments.</p>}</div></div></div><div className="mt-6 lms-card rounded-3xl p-6"><h3 className="font-semibold">Courses</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{data.courses.map(c=><div key={c.id} className="rounded-xl border border-white/10 p-4"><p className="font-medium">{c.title}</p><p className="mt-1 text-xs text-white/35">{c.description}</p></div>)}</div></div></>}</div></section></AppLayout>
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-white/[.02] p-3"><p className="text-[11px] uppercase tracking-wider text-white/25">{label}</p><p className="mt-1 text-sm">{value}</p></div>}
