import {useEffect,useState} from "react"
import {BookOpen,ClipboardList,Clock3,TrendingUp,CheckCircle2} from "lucide-react"
import {useNavigate} from "react-router-dom"
import AppLayout from "../components/AppLayout"
import {apiJson} from "../api"
type R={id:number;title:string;assessments:number;submissions:number;graded:number;pending:number;average:number|null}
type D={courses:number;assessments:number;submissions:number;graded:number;pending_grading:number;average_marks:number|null;grading_rate:number;course_stats:R[];focus_course:string|null}
export default function TeacherInsights(){const navigate=useNavigate();const [data,setData]=useState<D|null>(null);const [error,setError]=useState("");useEffect(()=>{if(!localStorage.getItem("token")){navigate("/login");return}apiJson<D>("/teacher/insights").then(setData).catch(e=>setError(e instanceof Error?e.message:"Failed to load insights"))},[navigate]);return <AppLayout title="Teaching Insights" subtitle="Teacher Intelligence"><section className="lms-grid min-h-[calc(100vh-76px)] p-4 sm:p-6 lg:p-10"><div className="mx-auto max-w-6xl">{error&&<div role="alert" className="rounded-2xl border border-red-400/20 bg-red-400/10 p-5 text-sm text-red-300">{error}</div>}{data&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<BookOpen size={18}/>} label="Courses" value={data.courses}/><Metric icon={<ClipboardList size={18}/>} label="Assessments" value={data.assessments}/><Metric icon={<Clock3 size={18}/>} label="Pending" value={data.pending_grading}/><Metric icon={<TrendingUp size={18}/>} label="Average marks" value={data.average_marks??"—"}/></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="lms-card rounded-3xl p-7"><h2 className="text-xl font-semibold">Course performance</h2><div className="mt-6 space-y-5">{data.course_stats.map(c=><div key={c.id}><div className="flex justify-between gap-3"><div><p className="text-sm font-medium">{c.title}</p><p className="mt-1 text-xs text-white/35">{c.assessments} assessments · {c.submissions} submissions · {c.pending} pending</p></div><span className="text-sm text-white/50">{c.average??"—"}</span></div><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width:Math.min(100,Math.max(0,c.average||0))+"%"}}/></div></div>)}</div></div><div className="space-y-5"><div className="lms-card rounded-3xl p-7"><div className="flex items-center gap-2"><CheckCircle2 className="text-emerald-300" size={18}/><h3 className="font-semibold">Grading progress</h3></div><p className="mt-4 text-3xl font-semibold">{data.grading_rate}%</p><p className="mt-1 text-xs text-white/35">{data.graded} of {data.submissions} graded</p></div><button onClick={()=>navigate("/assignments")} className="lms-btn-primary w-full rounded-xl py-3 text-sm">Open assessments</button></div></div></>}</div></section></AppLayout>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number|string}){return <div className="lms-stat rounded-2xl p-5"><div className="lms-icon mb-4 flex h-10 w-10 items-center justify-center rounded-xl">{icon}</div><p className="text-sm text-white/40">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
